#!/usr/bin/env bash
#This script nstall nginx and starts it

sudo apt-get update -y 
sudo apt-get -y install nginx

sudo service nginx start
echo "Hello World" | sudo tee /var/www/html/index.html 
sudo service ngnx start
