#!/usr/bin/env bash
#This sript is used to setup and configure a load balancer


sudo apt-get update -y
sudo apt-get install -y haproxy

echo "global
    log 12.0.0.1 local0 notice
    maxconn 2048
    user haproxy
    group haproxy
defaults 
    log global
    mode http
    option htttplog
    option dontlognull
    retries 3
    option http-server-close
    option http-pretend-keepalive
    option redispatch
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000
frontend my frontend
    bind *:80
    default_backend mybackend
backend mybackend
    balance roundrobin
    server 253705-web-02 54.144.135.202 check
    server 253705-lb-01 34.229.136.194 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
