#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi

# MySQL root password
mysql_root_password="$1"

# Directory to store backups
backup_dir="/home/ubuntu/backup_mysql/"

# Create a timestamp for the archive name (day-month-year)
timestamp=$(date +%d-%m-%Y)

# MySQL dump file name
mysql_dump_file="backup.sql"

# Compressed archive name
archive_name="$timestamp.tar.gz"

# Path to store the backup files
backup_path="$backup_dir"

# Create the backup directory if it doesn't exist
mkdir -p "$backup_path"

#Generate MySQL dump
mysqldump -u root -p"$mysql_root_password" --all-databases > "$backup_path/$mysql_dump_file"

# Check if the MySQL dump was successful
if [ $? -eq 0 ]; then
    echo "MySQL dump successful."

    # Compress the dump into a tar.gz archive
    tar -czf "$backup_dir/$archive_name" -C "$backup_path" "$mysql_dump_file"

    # Check if the compression was successful
    if [ $? -eq 0 ]; then
        echo "Backup completed successfully. Archive: $archive_name"
        # Optionally, you can remove the temporary backup files
        #rm -rf "$backup_path"
    else
        echo "Error: Compression failed."
    fi
else
    echo "Error: MySQL dump failed."
fi
