#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

iterate=0
while [ $iterate -lt 10 ];do
	if [ $iterate -eq 8 ];then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	iterate=$((iterate + 1))
done
