#!/usr/bin/env bash
#This demonstrates a clock

hour=0

# Use a while loop to display time for 12 hours
while [ $hour -lt 13 ]; do
    echo "Hour: $hour"
    minute=1

    while [ $minute -lt 60 ]; do
        echo $minute
        minute=$((minute + 1))
    done

    hour=$((hour + 1))
done

